name: CI/CD Pipeline
on:
  push:
    branches:
      main

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Cache Maven packages
        
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run Tests
        run: mvn -B test

 
  build:

    name: Build
    needs: tests
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
     
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: target/data-0.0.1-SNAPSHOT.jar
            
  deploy:

    needs: build
    name: Deploy
    
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        
        uses: actions/download-artifact@v3
        with:
          name: artifact
      
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         # aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          use_existing_version_if_available: true
          application_name: spring-demo
          environment_name: Springdemo-env
          version_label: ${{github.SHA}}
          region: us-east-2
          deployment_package: data-0.0.1-SNAPSHOT.jar